config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "guides#index"
  resources :users, only: [:edit, :update] 
  resources :likes, only: :index
  resources :guides, only: :show do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    resources :pictures, only: :index
    member do
      post 'pay'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :guide

  validates :text, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/guide.rb
class Guide < ApplicationRecord
  has_many :users, through: :user_guides
  has_many :likes
  has_many :comments
  has_many :user_guides
  has_many :pictures
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :guide
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :guide
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes
  has_many :guides, through: :user_guides
  has_many :comments
  has_many :user_guides

  validates :name, presence: true, uniqueness: true
  mount_uploader :image, ImageUploader
end

app/models/user_guide.rb
class UserGuide < ApplicationRecord
  belongs_to :user
  belongs_to :guide
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/guides/#{comment.guide.id}" 
  end
  
  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, guide_id: params[:guide_id])
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  require 'payjp'
  before_action :set_guide, only: [:pay, :show]
  before_action :set_like, only: [:index, :show]
  before_action :set_sold, only: [:index, :show]

  def pay
    Payjp.api_key = "sk_test_75a1cf07d11562a783711721"
    Payjp::Charge.create(
      amount: @guide.price, 
      card: params['payjp-token'], 
      currency: 'jpy'
    )
    @user_guide = UserGuide.new(user_id: current_user.id, guide_id: @guide.id)
    if @user_guide.save
      redirect_to guide_pictures_path(@guide.id)
    else
      redirect_to guide_path(@guide.id)
    end
  end

  def index
    return nil if params[:keyword] == ""
    @guides_key = Guide.where(['title LIKE ?', "%#{params[:keyword]}%"] )
    respond_to do |format|
      format.html
      format.json
    end
    @guides_hokkaido = Guide.where(area: "北海道")
    @guides_tohoku = Guide.where(area: "東北")
    @guides_kantou = Guide.where(area: "関東")
    @guides_tokai = Guide.where(area: "東海")
    @guides_kansai = Guide.where(area: "関西")
    @guides_chugoku = Guide.where(area: "中国")
    @guides_shikoku = Guide.where(area: "四国")
    @guides_kyushu = Guide.where(area: "九州")
  end

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
    @comments = @guide.comments.includes(:user)
    @likes_count = Like.where(guide_id: @guide.id).count
  end

  private

  def set_guide
    @guide = Guide.find(params[:id])
  end

  def set_like
    @likes = Like.where(user_id: current_user.id)
  end

  def set_sold
    @solds = UserGuide.where(user_id: current_user.id)
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = Like.new(
      user_id: current_user.id,
      guide_id: params[:guide_id]
    )
    like.save
    redirect_to "/guides/#{like.guide.id}"
  end

  def destroy
    like = Like.find_by(
      user_id: current_user.id,
      guide_id: params[:guide_id]
    )
    like.destroy
    redirect_to "/guides/#{like.guide.id}"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.where(guide_id: params[:guide_id])
    @likes = Like.where(user_id: current_user.id)
    @solds = UserGuide.where(user_id: current_user.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guides/_header.html.haml
.header
  = link_to root_path, class: "header__logo" do
    Travel Geographic

app/views/guides/_show_guide.html.haml
.show-guide
  %img.show-guide__image{src: @guide.image, alt: "ガイドトップ写真"}
  .show-guide__title
    .title
      = @guide.title
    .like
      - if Like.find_by(user_id: current_user.id, guide_id: @guide.id)
        = link_to guide_like_path(@guide.id), class: 'like-btn', method: :delete do
          = icon("fas", "heart")
      - else
        = link_to guide_likes_path(@guide.id), class: 'unlike-btn', method: :post do
          = icon("far", "heart")
      = @likes_count
  .show-guide__outline
    = @guide.body
  .show-guide__detail
    - if UserGuide.find_by(user_id: current_user.id, guide_id: @guide.id)
      = link_to guide_pictures_path(@guide.id), class: "next-btn" do
        続きを読む
    - else
      支払い金額￥
      = @guide.price 
      = form_tag pay_guide_path do
        :plain
        %script{type: "text/javascript", src: "https://checkout.pay.jp", class:"payjp-button", "data-text": "購入する", "data-key": "pk_test_6b475e7b2164c361b2105454"}
  .show-guide__form-area
    = form_for [@guide, @comment] do |f|
      = f.text_field :text, class: "form-message", placeholder: "コメントを書く（任意）"
      = f.submit "送信", class: "form-btn"
  .show-guide__comment
    .contents
      - @comments.each do |comment|
        .content
          .content__items
            .user
              %img.user__image{src: comment.user.image, alt: "プロフィール写真"}
              .user__name
                = comment.user.name
          .content__message
            = comment.text

app/views/guides/_side_bar.html.haml
.side-bar 
  .side-bar__user
    .top-items
      .top-items__user
        %img.top-items__user__image{src: current_user.image, alt: "プロフィール写真"}
        .top-items__user__name
          = current_user.name
      .top-items__icon
        = link_to edit_user_path(current_user), class: "setting-btn" do
          = icon('fas', 'cog')
  .side-bar__like
    .title
      = icon('fas', 'thumbs-up')
      いいね
    .contents
      - @likes.each do |like|
        = link_to guide_path(like.guide.id) do
          %img.contents__image{src: like.guide.image, alt: "ガイドトップ画像"}
  .side-bar__buy
    .title
      = icon('fas', 'shopping-cart')
      購入済みガイド
    .contents
      - @solds.each do |sold|
        = link_to guide_path(sold.guide.id) do
          %img.contents__image{src: sold.guide.image, alt: "ガイドトップ画像"}

app/views/guides/index.html.haml
.wrapper
  = render "header"
  = render "side_bar"
  = render "main_guide"

app/views/guides/show.html.haml
.wrapper
  = render "header"
  = render "side_bar"
  = render "show_guide"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title GeoApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
  %body
    = yield

app/views/pictures/_detail.html.haml
.detail_guide
  .contents
    .content
      - @pictures.each do |picture|
        %img.content{src: picture.picture, alt: "guide"}

app/views/pictures/index.html.haml
.wrapper
  = render "/guides/header"
  = render "/guides/side_bar"
  = render "detail"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 編集
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name, "名前"
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :image, "プロフィール画像"
          .field-input
            = f.file_field :image
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "更新", class: 'btn'